<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <AssemblyName>Runbook.Protocol</AssemblyName>
    <RootNamespace>Runbook.Protocol</RootNamespace>
    <OutputType>Library</OutputType>
  </PropertyGroup>

</Project>
